version: '3.8'

# define different containers and a volume
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn arch_demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1336:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: